services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Porta externa alterada para 5433
  web:
    build: .
    environment:
      # Variáveis de ambiente para o Django (serviço 'web')
      # Usadas pelo python-decouple no settings.py
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db # O nome do serviço do banco de dados no Docker Compose
      POSTGRES_PORT: 5432
      PYTHONPATH: /app
    # O comando WSGI foi corrigido para o caminho correto
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db